CREATE TABLE IF NOT EXISTS patients (
                                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    email         VARCHAR(255) NOT NULL UNIQUE,
password      VARCHAR(255) NOT NULL,
id_card_no    VARCHAR(50)  NOT NULL UNIQUE,
first_name    VARCHAR(100) NOT NULL,
last_name     VARCHAR(100) NOT NULL,
phone_number  VARCHAR(30),
birthday      DATE
);